name: ons
version: "1.0.0"
config-version: 2

profile: ons

model-paths: ["models"]
macro-paths: ["macros"]

models:
  ons:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
